### ISSUE TITLE
扫码器闪退

### ISSUE THREAD

**Issue by Phos39** [Haocen2004/bh3_login_simulation#1]
服务器 B服
扫码后确认登录时闪退，游戏被扫码但未确认登录
目前尝试过氢OS和funthouch OS均会闪退

**Comment by Haocen2004** [comment]
扫码器是否为最新测试版

**Comment by Phos39** [comment]
> 扫码器是否为最新测试版

1.1.1 alpha2，B站置顶动态的蓝奏云链接下载的

**Comment by Haocen2004** [comment]
fixed
