### ISSUE TITLE
闪退  空指针 米服

### ISSUE THREAD

**Issue by beater-kirito** [Haocen2004/bh3_login_simulation#17]
![Screenshot_2022-02-22-21-24-44-149_com miui bugre](https://user-images.githubusercontent.com/66652239/155142565-61423c28-5326-469a-92fe-0090f6652a2b.jpg)

log

**Comment by Haocen2004** [comment]
miui游戏服务bug 卸载更新或停用

**Comment by Haocen2004** [comment]
在dev分支应用了强制阻止连接游戏服务 处理用户需要游戏服务情况

**Comment by beater-kirito** [comment]
> 在dev分支应用了强制阻止连接游戏服务 处理用户需要游戏服务情况

大佬啥时候发个realease包呢

**Comment by beater-kirito** [comment]
> > > 在dev分支应用了强制阻止连接游戏服务 处理用户需要游戏服务情况
> > 
> > 
> > 大佬啥时候发个realease包呢
> 
> 比较急的话群里有测试版 大概周末可以更新下个release 因为改后台啥的有电脑会比较好弄

可惜电脑莫得安卓环境了，以后用不到也不想再装回来
