### ISSUE TITLE
小米服wsa登录失败

### ISSUE THREAD

**Issue by Haocen2004** [Haocen2004/bh3_login_simulation#18]
-102
[{level='长按', TAG='复制日志', message='长按该条复制所有'}, {level='DEBUG', TAG='SPCheck', message='初始化检查中...'}, {level='DEBUG', TAG='SPCheck', message='检查赞助者账号及自动登陆信息中...'}, {level='DEBUG', TAG='AutoLogin', message='无自动登陆任务 上次登陆情况：false 当前是否已有登陆进程：false'}, {level='DEBUG', TAG='SPCheck', message='无自动更新 - 无自动登陆 - 当前线程结束'}, {level='DEBUG', TAG='LogLiveData', message='load log data'}, {level='DEBUG', TAG='LogLiveData', message='load log data'}, {level='DEBUG', TAG='SPCheck', message='初始化检查中...'}, {level='DEBUG', TAG='SPCheck', message='检查赞助者账号及自动登陆信息中...'}, {level='DEBUG', TAG='AutoLogin', message='无自动登陆任务 上次登陆情况：false 当前是否已有登陆进程：false'}, {level='DEBUG', TAG='SPCheck', message='无自动更新 - 无自动登陆 - 当前线程结束'}, {level='INFO', TAG='MiLogin', message='finishInitProcess: Init success'}, {level='DEBUG', TAG='MiLogin', message='err:+-102'}, {level='DEBUG', TAG='LogLiveData', message='load log data'}]

**Comment by Haocen2004** [comment]
貌似是小米sdk问题
可用wsa模拟arm8模式正常登录

**Comment by beater-kirito** [comment]
好家伙，这是拿issues当笔记用呢 （手动狗头）

**Comment by Haocen2004** [comment]
本来不应该是我创建issue的 但有些人不太会用（
